project:
  type: book

book:
  title: "book-test"
  author: "Teig Johansen"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - embedded-cpp-demo.qmd
    - local-llm-morpheus-install.qmd
    - handwriting-to-code.qmd
    - summary.qmd
    - references.qmd
jupyter: xcpp17

bibliography: references.bib

format:
  html:
    theme:
      - darkly
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    lightbox: true
  pdf:
    documentclass: scrreprt



